{% set version = "0.3-0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-flux
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/flux_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/flux/flux_{{ version }}.tar.gz
  sha256: af0c9f0265feda053d5f95a5d81a4bb2051ca5545572da6590c8d9be42cc71f6

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-catools
  run:
    - r-base
    - r-catools

test:
  commands:
    - $R -e "library('flux')"           # [not win]
    - "\"%R%\" -e \"library('flux')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=flux
  license: GPL-2.0-only
  summary: 'Functions for the calculation of greenhouse gas flux rates  from closed chamber concentration measurements. The package follows  a modular concept: Fluxes can be calculated in just two simple steps  or in several steps if more control in details is wanted. Additionally  plot and preparation functions as well
    as functions for modelling gpp and reco are provided.'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
