travis:
  secure:
    BINSTAR_TOKEN: NW17rhj58Bmx5IRNqMGYJy1MqGG7o3+eCWH4w2VLQ8wlIOdVkR21roq3vjHEJDrVtsmf6XPjmIyRmWpI7YIolee2oumJFxuxHq02DOyk+Gm9xZZmX6aJQA61QfAd+89O0EeAsdsNmrw7DFkmgUirVkSyrhv2s92nMYwqReHZOX7xvdLk3XupPikEOd5p8r3sEEBI9121nAC6wyHPYIOXoHVxQeLKdFALTP4alhrYakKOeyr+a9jd3fnI81U/jOspPOz793Z3jf2YPlsYNgHbs7sMRHYKxCVY0XvBhBJbAalR1Gd4OS8FE1oDFZHtA82uiiCtwEb8qMAG8XMM9quLnN/oI1XjZhYTom0FGJwQH+LOaxP9xThFEp8K9G5RI7FxcsuZsgWTrYcIGyDapdb7krrYwLTke/RvmI1Q2/JbJGOInjldgYhkLi3vFXPb1WSBEotwd9GdK9QZY77uE+1Be54HV9cJF+KQau1bbG0wbCeOG8MfEfA57StPcFCNa9rnVdSZ5EQw2cMAUVJ+/W2hYn93yNiOFxWpW0Z/No8nxDAlPvnlp7B96l0bHIpIbI1D3X2R9et3y09QSjx6XzbrRSm8NNP3LJyMwrjlAiQPJs5mJCfagLV5IebCIDKVLdcmF5EF9ZC3ukhRR3SKMmg2r9onNzSJqTDbbn3Cr3bSuOE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
