appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: OxgBv7jSNz7rq3yi0OlGYgdFRzw6GjnSQG+EJ8L/cACsb7C2vHp2Vs/nutqKnpXgEZ3wu/OfwWtd4m3F7vgRqbLpzsLx5rysfyzvlC/HxoF+L4VOJKYNqHrZu3M9R3081JnnGZO1FJRJjpO/Lrjsr1W75U7tOLWZTxY3PJQ/Y4VnRNZa3pUpzexu8XZOgi7EC1P+Sfg+KrHUhDt8yulyq/hVdgqtNCfTHrenr5hPHp/RI31sS94ebJ+XwzKr+fis+YLqGdLdejDOW95kAXq4lqtFGlzBCmWdposmt6lTp6Z+kj+yU7QOKawdsP4D2aVMoNC+UuGyTnxuPz3Kf+pqep1ZQ6pcXAHLRgQUUEll/m/ntxMm09GpzxJFGYDxSIT94dtew3/LO39R+TsMLN0Lk02tOtEiZrv9+8TD1pmrCzsfc3I0MR7JnnAJqoz62HopaMQwYg+5t6EPO+TT8iMSb5OO5dXu7EvaP0OOBR7YWOpO++PU74qc8YJtpmT0yhis3Nx5eN3uNn4PHuv+XvVmXbVfxAruVlN60Apg/ecvvPBrLnKpNsaGXUBRKtgALXd/rpGw0hICFuX/K0XcQsqRr6kqkKILzx0qUFBfRTfkGZCmX6vnituxYoPT9G5CrUzsuQYr2ZKshAvbRDoLsrqzPeySe9wz3JWqdWnEhaXLa4w=}
