travis:
  secure:
    BINSTAR_TOKEN: oHM3gk3qa9LVgdgiv3MyYA2HtAqZwgyN+UaIbKuWFtNtwWJyR5OzZzmOcxyHwsu1JuVWF7gA7Wy9AF+glfU/qEoGKx5snoGe5zUu/v1yiHdKeTt9X2AY/NMUAZEPUBCqfQo0Zyovz91WsqlF0ZytrPxvWXt+qU9ywW1yTWMmyhdLfpCeixZTzY3PhhXBJEekX/eq36Mmp8mfhvhkCGrba01kdCoQr8acsQUv2CmBHnnsMpCuaBbB49oj/D6vHtpUQktwSFDzREI5Xvp/XhPg4FuCwdO5M16KsUvpPrCivd1dEGo16VVN2QuKH3FFlk66BPGs/FovfVe1wgM3sUY4z2INF6CyMBp7TP9LEEF4gdBi4KJ69TLXRYhlt27g8h3QkTab3PPoRtL5aIj7rImFbRrFoqegIwZMBaTtu3PI8+kffNF1aquao1VmJk6MLi4Zkasr7fF3y1UIZnHZg8oOm5bRjLNhVqpEHEwrMcCk1mNb5eWZ/9EU+KCHfiBbHnxBSdbRhwwDNG5R5xHAhR2mCaZYc+PaSOTV4dHUzkl4aRjSAX9+Gh8m+W3k6A9c8ijKpcJ/JQ661D86JdJthEh1e8WryJl0ykBKq2hJ1i4qR8wy3X60LqZBhKtbv+u6NvJa0tUXD1vbuhnrGJDZsIdv+8r4gurpTAOk0vYBOahcVgw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
