travis:
  secure:
    BINSTAR_TOKEN: WogMrCAU9stAUFukBye/rMwA3bZYsWqjSxRFY243u+UF24rdptrDirpZbhPLJ5S3XgJD5X5TQXys+VSJbFxZf91PwlH/Hy/x9D7yIh8cOPr5w1IpEqTzebwlMQ2y4IFREBhjrpzmQ99bv1GOnYU4aj1+o53rf0U38ztKnof46lDPj1AdpJ2uA5ihtjyLQOXeK4LRRGEUfHI0Dz2yfqlO0o6iUX3UNKuQR/K01RVfMfygnKRFrW435RcfpcVAn3bgAHMbwKX7g1i/9IroRTC7dyHv13ay8Pzbts26N05evXqUlO2OEHzDwNaIQWTeUOxsA/BntbR8IvsVdz/14I6pv4jAjTTRsdRSWxIMQv3aMu1Kn1bEGK66vH+er+vyKauhkSYU/j6alnPDrLOuLVdOtMeRrdVW599wO4RlpppOxehL7iA1yVY4V5PdZxrIXekdGjLYV0XP+mEN9gTAboGp2+9dtHjCJ3VWjs1J3voYMT9K8K7vS8+MnySsfMAkWW6TcsVVQ4YXyF5MdepRmnUw94am4N8ItzLzwFgGdqY6P1eUU4mN1Apsp8GsrOfQxAvLVtZOJXfATWeWle95ThXBnuN45c8eKiu5BMuAGoOShuZw72gMz31/RZmxNHFtk18Cy+LRofDtEnkRZ/8GiMaOuxdWzQt6IwU11hMeK+D3cfs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
